- hosts: db
  vars_files:
    - db_credentials_{{ env }}.yml
  become: true
  roles:
    - db

- hosts: web
  vars:
    site_name: example.com
    db_host: "{{ groups['db'][0] }}"
  vars_files:
    - web_credentials_{{ env }}.yml
    - db_credentials_{{ env }}.yml
  become: true
  roles:
    - web
