---
- name: Install mariadb, PyMySQL
  apt:
    name: [mariadb-server, python3-pymysql]
    state: present
    update_cache: true
  notify: restart_mariadb

- name: Create user
  mysql_user:
    login_unix_socket: "{{ login_socket }}"
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    host: "%"
    priv: "{{ db_name }}.*:all"

- name: Create database
  mysql_db:
    login_unix_socket: "{{ login_socket }}"
    name: "{{ db_name }}"
    state: present
  register: db_status
  
- name: Copy db init
  copy:
    src: init.sql
    dest: /tmp/
  when: db_status.changed

- name: Init db
  mysql_db:
    login_unix_socket: "{{ login_socket }}"
    name: "{{ db_name }}"
    state: import
    target: /tmp/init.sql
  when: db_status.changed

- name: Populate db
  mysql_query:
    login_unix_socket: "{{ login_socket }}"
    login_db: "{{ db_name }}"
    query: insert into users (name, email) value ('{{ item.key }}', '{{ item.value.email }}')
  with_dict:
    John Doe:
      email: john.doe@example.com
    Jane Smith:
      email: jane.smith@example.com
    Alice Johnson:
      email: alice.johnson@example.com
    Bob Brown:
      email: bob.brown@example.com
    Charlie Davis:
      email: charlie.davis@example.com
  when: db_status.changed
