---
- name: Add ondrej/php PPA repository
  apt_repository:
    repo: 'ppa:ondrej/php'
    state: present

- name: Install nginx
  apt:
    name: [nginx, php8.1-fpm, php8.1-mysqlnd]
    state: present
    update_cache: true

- name: Add site
  template:
    src: site_config
    dest: /etc/nginx/sites-available/{{ site_name }}
  notify: restart_nginx

- name: Link site
  file:
    src: /etc/nginx/sites-available/{{ site_name }}
    dest: /etc/nginx/sites-enabled/{{ site_name }}
    state: link
  notify: restart_nginx

- name: Add pages
  copy:
    src: pages/
    dest: /var/www/{{ site_name }}

- name: Add db_credentials.ini
  template:
    src: db_credentials.ini
    dest: /var/www/{{ site_name }}
